### ISSUE TITLE
Error reading relinquishDefault of largeAnalogValue

### ISSUE THREAD

**Issue by trapperl** [JoelBender/BACpypes3#46]
I think this is a similar problem as the covIncrement Issue from yesterday.

I found a table saying that relinquishDefault should be a Double.
After changing it form Integer to Double, the error went away.
[https://bacnet.org/wp-content/uploads/sites/4/2022/08/Add-135-2008w.pdf](url)

python read-property.py 10.102.15.56 largeAnalogValue:2 relinquishDefault
`Traceback (most recent call last):
  File "/home/pses/site_level_controller/bacnet_interface/read-property.py", line 97, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/pses/site_level_controller/bacnet_interface/read-property.py", line 71, in main
    response = await app.read_property(
  File "/home/pses/site_level_controller/.venv/lib/python3.10/site-packages/bacpypes3/service/object.py", line 146, in read_property
    property_value = response.propertyValue.cast_out(property_type)
  File "/home/pses/site_level_controller/.venv/lib/python3.10/site-packages/bacpypes3/constructeddata.py", line 1751, in cast_out
    result = cls.decode(tag_list)
  File "/home/pses/site_level_controller/.venv/lib/python3.10/site-packages/bacpypes3/primitivedata.py", line 1134, in decode
    raise InvalidTag("integer application tag expected")
bacpypes3.errors.InvalidTag: integer application tag expected`

**Comment by JoelBender** [comment]
Correct, thank you.  Apparently the list of contributors is from accepting pull requests, but I'm considering you as one anyway :-).
